spring:
  datasource:
    url: jdbc:postgresql://192.168.22.115:5432/SpringBootHomeWork9
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: DataBasePcGame

#spring.datasource.url=jdbc:postgresql://192.168.22.115:5432/SpringBootHomeWork9
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.application.name=DataBasePcGame


management:
  endpoints:
    web:
      exposure:
        include: "metrics, prometheus"

#  endpoint:
#    health:
#      show-details: "always"
#management.endpoint.web.exposure.include=*
#
#server.port=8081

server:
  port: 8081









