server:
  port: 8765




spring:
  application:
    name: Api-GateWay
  cloud:
    gateway:
      routes:
        - id: HomePagePcGame
          uri: http://192.168.22.69:8080/
          predicates:
            - Path=/**
#        - id: Microservice2
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/serviceB/**

