spring:
  datasource:
    url: jdbc:postgresql://192.168.77.137:5432/SpringBootHomeWork9
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: DataBasePcGame



server:
  port: 8081








